In [1]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df.head()

index  encounter_id  patient_id             race  gender      age weight  \
0  69375     197029140    51521940         Hispanic    Male  [80-90)      ?   
1  57272     163571946    92631357        Caucasian    Male  [60-70)      ?   
2  82347     256497366    30023982        Caucasian  Female  [50-60)      ?   
3  89608     289891212    93606021  AfricanAmerican  Female  [70-80)      ?   
4  24091      81873900    23464296        Caucasian    Male  [70-80)      ?   

   time_in_hospital medical_specialty  num_lab_procedures  ...  X19   X20  \
0                 4  Emergency/Trauma                  39  ...   No    No   
1                 3  Emergency/Trauma                  34  ...   No    No   
2                 6        Nephrology                  50  ...   No  Down   
3                 5                 ?                  63  ...   No  Down   
4                 9        Psychiatry                  17  ...   No    No   

   X21  X22  X23 X24 X25 change diabetesMed  readmitted  
0   No   No   No  No  No     No         Yes           1  
1   No   No   No  No  No     No          No           0  
2   No   No   No  No  No     Ch         Yes           1  
3   No   No   No  No  No     Ch         Yes           1  
4   No   No   No  No  No     No          No           1  

[5 rows x 49 columns]

In [4]:
df.tail()

index  encounter_id  patient_id       race  gender      age weight  \
66582  39934     124202466    23450508  Caucasian  Female  [70-80)      ?   
66583  47366     145667070    29324601  Caucasian    Male  [80-90)      ?   
66584  76555     231061116     2179062  Caucasian  Female  [60-70)      ?   
66585  25392      84911682    20531754          ?  Female  [80-90)      ?   
66586  51312     153167502    81985473  Caucasian  Female  [80-90)      ?   

       time_in_hospital medical_specialty  num_lab_procedures  ...  X19  \
66582                11  InternalMedicine                  40  ...   No   
66583                 4                 ?                  39  ...   No   
66584                 2                 ?                  24  ...   No   
66585                 4  InternalMedicine                  39  ...   No   
66586                 2                 ?                  38  ...   No   

          X20  X21  X22  X23 X24 X25 change diabetesMed  readmitted  
66582  Steady   No   No   No  No  No     No         Yes           0  
66583      No   No   No   No  No  No     No          No           1  
66584      No   No   No   No  No  No     No         Yes           1  
66585      No   No   No   No  No  No     No          No           0  
66586  Steady   No   No   No  No  No     Ch         Yes           1  

[5 rows x 49 columns]

In [5]:
df.describe

<bound method NDFrame.describe of        index  encounter_id  patient_id             race  gender      age  \
0      69375     197029140    51521940         Hispanic    Male  [80-90)   
1      57272     163571946    92631357        Caucasian    Male  [60-70)   
2      82347     256497366    30023982        Caucasian  Female  [50-60)   
3      89608     289891212    93606021  AfricanAmerican  Female  [70-80)   
4      24091      81873900    23464296        Caucasian    Male  [70-80)   
...      ...           ...         ...              ...     ...      ...   
66582  39934     124202466    23450508        Caucasian  Female  [70-80)   
66583  47366     145667070    29324601        Caucasian    Male  [80-90)   
66584  76555     231061116     2179062        Caucasian  Female  [60-70)   
66585  25392      84911682    20531754                ?  Female  [80-90)   
66586  51312     153167502    81985473        Caucasian  Female  [80-90)   

      weight  time_in_hospital medical_specialty  num

In [6]:
df = df.drop(['index', 'encounter_id', 'race', 'medical_specialty', 'weight'], axis=1)

In [7]:
Age = []
for i in df['age']:
  if i == '[80-90)':
    Age.append(85)
  elif i == '[60-70)':
    Age.append(65)
  elif i == '[50-60)':
    Age.append(55)
  elif i == '[70-80)':
    Age.append(75)
  elif i == '[40-50)':
    Age.append(45)
  elif i == '[20-30)':
    Age.append(25)
  elif i == '[30-40)':
    Age.append(35)
  elif i == '[90-100)':
    Age.append(95)
  elif i == '[0-10)':
    Age.append(5)
  else:
    Age.append(15)

In [8]:
df['age'] = Age

In [9]:
df.age

0        85
1        65
2        55
3        75
4        75
         ..
66582    75
66583    85
66584    65
66585    85
66586    85
Name: age, Length: 66587, dtype: int64

In [10]:
###replacing miss values in diag_1 to diag_4
###replacing miss values in diag_1 to diag_4
df['diag_1'] =  pd.to_numeric(df['diag_1'].apply(lambda x: np.nan if x[0].isnumeric() == False else x))
df['diag_2'] =  pd.to_numeric(df['diag_2'].apply(lambda x: np.nan if x[0].isnumeric() == False else x))
df['diag_3'] =  pd.to_numeric(df['diag_3'].apply(lambda x: np.nan if x[0].isnumeric() == False else x))
df['diag_4'] =  pd.to_numeric(df['diag_4'].apply(lambda x: np.nan if x[0].isnumeric() == False else x))

In [11]:
df['diag_1'].fillna(df['diag_1'].mean(), inplace=True)
df['diag_2'].fillna(df['diag_1'].mean(), inplace=True)
df['diag_3'].fillna(df['diag_1'].mean(), inplace=True)
df['diag_4'].fillna(df['diag_1'].mean(), inplace=True)

In [12]:
#for columns from X1 to x25
df['X1'].unique()

array(['None', '>200', 'Norm', '>300'], dtype=object)

In [13]:
df['X2'].unique()

array(['None', 'Norm', '>8', '>7'], dtype=object)

In [14]:
df['X3'].unique()

array(['No', 'Steady', 'Up', 'Down'], dtype=object)

In [15]:
df['X4'].unique()

array(['No', 'Steady', 'Up', 'Down'], dtype=object)

In [16]:
df['X5'].unique()

array(['No', 'Steady', 'Down', 'Up'], dtype=object)

In [17]:
df['X6'].unique()

array(['No', 'Steady', 'Up'], dtype=object)

In [18]:
df['X7'].unique()

array(['No', 'Steady', 'Up', 'Down'], dtype=object)

In [19]:
df['X8'].unique()

array(['No'], dtype=object)

In [20]:
df['X9'].unique()

array(['No', 'Steady', 'Up', 'Down'], dtype=object)

In [21]:
df['X10'].unique()

array(['No', 'Down', 'Steady', 'Up'], dtype=object)

In [22]:
df['X11'].unique()

array(['No', 'Steady'], dtype=object)

In [23]:
df['X12'].unique()

array(['No', 'Steady', 'Down', 'Up'], dtype=object)

In [24]:
df['X14'].unique()

array(['No', 'Steady', 'Up', 'Down'], dtype=object)

In [25]:
df['X15'].unique()

array(['No', 'Down', 'Steady'], dtype=object)

In [26]:
df['X16'].unique()

array(['No', 'Steady'], dtype=object)

In [27]:
df['X17'].unique()

array(['No', 'Steady'], dtype=object)

In [28]:
df['X18'].unique()

array(['No'], dtype=object)

In [29]:
df['X19'].unique()

array(['No'], dtype=object)

In [30]:
df['X20'].unique()

array(['No', 'Down', 'Up', 'Steady'], dtype=object)

In [31]:
df['X21'].unique()

array(['No', 'Steady', 'Down', 'Up'], dtype=object)

In [32]:
df['X22'].unique()

array(['No', 'Steady'], dtype=object)

In [33]:
df['X23'].unique()

array(['No', 'Steady'], dtype=object)

In [34]:
df['X24'].unique()

array(['No', 'Steady'], dtype=object)

In [35]:
df['X25'].unique()

array(['No'], dtype=object)

In [36]:
df = df.drop(['X6', 'X8', 'X11', 'X15', 'X16', 'X17', 'X18', 'X19', 'X22', 'X23', 'X24', 'X25'], axis=1)

In [37]:
df.columns

Index(['patient_id', 'gender', 'age', 'time_in_hospital', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3',
       'diag_4', 'diag_5', 'number_diagnoses', 'X1', 'X2', 'X3', 'X4', 'X5',
       'X7', 'X9', 'X10', 'X12', 'X13', 'X14', 'X20', 'X21', 'change',
       'diabetesMed', 'readmitted'],
      dtype='object')

In [38]:
cval = ['None', 'Norm', '>8', '>7', '>200', '>300','No', 'Steady', 'Up', 'Down']

In [39]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [40]:
cval2 = label_encoder.fit_transform(cval)

print(cval2)

[6 7 3 2 0 1 5 8 9 4]


In [41]:
df.replace(cval, cval2, inplace=True)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66587 entries, 0 to 66586
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   patient_id          66587 non-null  int64  
 1   gender              66587 non-null  object 
 2   age                 66587 non-null  int64  
 3   time_in_hospital    66587 non-null  int64  
 4   num_lab_procedures  66587 non-null  int64  
 5   num_procedures      66587 non-null  int64  
 6   num_medications     66587 non-null  int64  
 7   number_outpatient   66587 non-null  int64  
 8   number_emergency    66587 non-null  int64  
 9   number_inpatient    66587 non-null  int64  
 10  diag_1              66587 non-null  float64
 11  diag_2              66587 non-null  float64
 12  diag_3              66587 non-null  float64
 13  diag_4              66587 non-null  float64
 14  diag_5              66587 non-null  float64
 15  number_diagnoses    66587 non-null  int64  
 16  X1  

In [43]:
df.isnull().sum()

patient_id            0
gender                0
age                   0
time_in_hospital      0
num_lab_procedures    0
num_procedures        0
num_medications       0
number_outpatient     0
number_emergency      0
number_inpatient      0
diag_1                0
diag_2                0
diag_3                0
diag_4                0
diag_5                0
number_diagnoses      0
X1                    0
X2                    0
X3                    0
X4                    0
X5                    0
X7                    0
X9                    0
X10                   0
X12                   0
X13                   0
X14                   0
X20                   0
X21                   0
change                0
diabetesMed           0
readmitted            0
dtype: int64

In [44]:
#creating dummy values for the categorical data

In [45]:
#for gender 
df['gender'].unique()

array(['Male', 'Female', 'Unknown/Invalid'], dtype=object)

In [46]:
g1 = ['Male', 'Female', 'Unknown/Invalid']
g2 = label_encoder.fit_transform(g1)

print(g2)

[1 0 2]


In [47]:
df['gender'].replace(g1, g2, inplace=True)

In [48]:
df['gender'].unique()

array([1, 0, 2])

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66587 entries, 0 to 66586
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   patient_id          66587 non-null  int64  
 1   gender              66587 non-null  int64  
 2   age                 66587 non-null  int64  
 3   time_in_hospital    66587 non-null  int64  
 4   num_lab_procedures  66587 non-null  int64  
 5   num_procedures      66587 non-null  int64  
 6   num_medications     66587 non-null  int64  
 7   number_outpatient   66587 non-null  int64  
 8   number_emergency    66587 non-null  int64  
 9   number_inpatient    66587 non-null  int64  
 10  diag_1              66587 non-null  float64
 11  diag_2              66587 non-null  float64
 12  diag_3              66587 non-null  float64
 13  diag_4              66587 non-null  float64
 14  diag_5              66587 non-null  float64
 15  number_diagnoses    66587 non-null  int64  
 16  X1  

In [50]:
#for change 
df['change'].unique()

array([5, 'Ch'], dtype=object)

In [51]:
ch1 = ['No', 'Ch']
ch2 = label_encoder.fit_transform(ch1)

print(ch2)

[1 0]


In [52]:
df['change'].replace(ch1, ch2, inplace=True)
df['change'].unique()

array([5, 0])

In [53]:
#for diabetesMed
df['diabetesMed'].unique()

array(['Yes', 5], dtype=object)

In [54]:
dm = ['Yes', 'No']
dm1 = label_encoder.fit_transform(dm)

print(dm1)

[1 0]


In [55]:
df['diabetesMed'].replace(dm, dm1, inplace=True)
df['diabetesMed'].unique()

array([1, 5])

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66587 entries, 0 to 66586
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   patient_id          66587 non-null  int64  
 1   gender              66587 non-null  int64  
 2   age                 66587 non-null  int64  
 3   time_in_hospital    66587 non-null  int64  
 4   num_lab_procedures  66587 non-null  int64  
 5   num_procedures      66587 non-null  int64  
 6   num_medications     66587 non-null  int64  
 7   number_outpatient   66587 non-null  int64  
 8   number_emergency    66587 non-null  int64  
 9   number_inpatient    66587 non-null  int64  
 10  diag_1              66587 non-null  float64
 11  diag_2              66587 non-null  float64
 12  diag_3              66587 non-null  float64
 13  diag_4              66587 non-null  float64
 14  diag_5              66587 non-null  float64
 15  number_diagnoses    66587 non-null  int64  
 16  X1  

In [57]:
#Creating a Model 
x = df.drop('readmitted', axis=1)
y = df['readmitted']

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=100)

In [60]:
from sklearn.metrics import confusion_matrix

In [61]:
from sklearn.metrics import accuracy_score

In [62]:
from sklearn.tree import DecisionTreeClassifier

In [63]:
clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)
clf.score(x_test, y_test)

0.723582119437353

In [64]:
predictions = clf.predict(x_test)

In [65]:
accuracy = confusion_matrix(y_test, predictions)
accuracy

array([[7993, 2758],
       [2764, 6462]])

In [66]:
predictions

array([0, 0, 0, ..., 0, 0, 1])

In [67]:
for i in predictions:
    print(i)

0
0
0
1
1
1
1
1
1
0
0
0
0
0
0
0
1
0
0
0
0
1
1
0
0
0
0
1
1
0
1
0
0
1
0
0
0
0
0
0
0
1
1
1
1
1
0
0
1
0
1
0
1
1
0
1
0
0
1
1
1
1
1
0
0
0
0
0
0
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
0
0
1
0
0
0
1
0
1
1
1
0
0
1
0
0
1
0
0
1
0
0
1
1
1
1
0
1
0
0
0
1
1
0
0
0
0
0
1
1
0
1
0
0
0
0
0
1
0
0
1
0
1
1
1
1
1
0
0
1
0
1
0
0
1
1
0
0
1
1
0
1
1
1
1
1
0
0
1
0
1
1
1
1
0
1
1
1
0
1
1
1
0
1
1
0
0
0
0
1
0
1
0
1
0
0
0
0
1
0
0
0
0
1
0
0
0
1
0
0
0
1
1
0
0
1
1
1
0
1
1
1
1
0
1
0
0
0
1
0
1
0
1
1
0
0
1
1
1
1
0
1
0
0
1
0
0
1
0
0
0
1
0
1
1
1
1
1
1
1
0
1
1
1
1
0
0
0
1
1
0
0
1
1
0
0
1
1
1
1
1
1
1
0
0
1
0
1
0
0
1
0
1
0
1
0
0
0
0
1
0
1
1
1
0
1
0
1
0
0
1
1
0
1
0
0
1
0
0
0
0
0
0
0
1
0
0
1
1
1
0
0
1
1
1
1
0
1
1
0
1
0
1
0
0
0
0
1
0
0
1
1
0
1
1
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
1
0
0
1
0
1
1
1
1
0
0
1
0
0
1
0
0
0
0
1
1
1
1
0
0
1
0
1
0
1
1
0
0
0
0
0
0
0
1
0
0
1
1
1
0
0
1
1
0
1
1
1
1
0
0
1
1
0
1
1
1
0
1
0
0
0
0
1
1
0
0
1
1
0
1
0
1
1
0
1
1
1
0
0
0
0
1
0
1
0
1
0
0
0
0
1
1
1
1
0
0
1
1
0
0
1
1
0
0
1
1
0
0
1
0
0
1
0
0
0
1
0
1
1
1
1
1
1
0
0
1
0


In [68]:
CSV = pd.DataFrame({'Readmitted': predictions})

In [69]:
df.isnull().sum()

patient_id            0
gender                0
age                   0
time_in_hospital      0
num_lab_procedures    0
num_procedures        0
num_medications       0
number_outpatient     0
number_emergency      0
number_inpatient      0
diag_1                0
diag_2                0
diag_3                0
diag_4                0
diag_5                0
number_diagnoses      0
X1                    0
X2                    0
X3                    0
X4                    0
X5                    0
X7                    0
X9                    0
X10                   0
X12                   0
X13                   0
X14                   0
X20                   0
X21                   0
change                0
diabetesMed           0
readmitted            0
dtype: int64

In [70]:
CSV.to_csv('predictions.csv', index=False)